development:
  adapter: mysql2
  encoding: utf8mb4
  database: website_dev
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8mb4
  database: website_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %> 